AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'db/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/views/**/*.json.jbuilder'

Metrics/AbcSize:
  Exclude:
    - 'app/views/**/*.json.jbuilder'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*_spec.rb'
