version: '3'

services:
  db:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  server:
    depends_on:
      - 'db'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    environment:
      RAILS_ENV: 'production'
    env_file:
      - '.env'
